### ISSUE TITLE
Retornar o usuário para a tela de login quando o token dele expirar.

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#28]
**Detalhes**: 
- o token do usuário expira depois de um dia que foi gerado.
- A API vai retornar um 401 e uma mesagem de "Token expired" quando o token do usuário ficar inválido.

**Rota**
- POST `/sessions`
Nessa rota deve ser enviado um body contendo o email e password do usuário, exemplo:
```json
{
    "email": "joaovictorramalho7@gmail.com",
    "password": "123"
}
```
Caso os dados estejam corretos a resposta vai ser:
```json
{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTAyOTQ4MjEsImV4cCI6MTY1MDM4MTIyMSwic3ViIjoiMTY3NDA3NWMtZDE5Yi00ZjM3LTg4OTgtYWJhMGNkN2IyZjg4In0.mJpOyFb5WAY-DkYO3Qe-unNJa04EzWtLTXlBt2qR_gg",
   "user": {
        "name": "João Victor ",
	"email": "joaovictorramalho7@gmail.com"
    }
}
```
Esse token deve substituir o token anterior no storage e **o usuário redirecionado para a home ou para a última tela que ele estava antes do logout.**

Assinada por: ninguém ainda.

**Comment by jvolima** [comment]
👋

**Comment by 404jv** [comment]
Fechado com a #35
