### ISSUE TITLE
Conectar a Home com o Backend.

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#31]
Grande parte dessa já foi feita por vocês @1SyuLi e @jvolima, agora só falta fazer o calculo de porcentagem e colocar a barra de progresso de forma dinâmica.

**Comment by 1SyuLi** [comment]
🧙‍♂️

**Comment by jvolima** [comment]
👏👏👏👏👏👏👏

**Comment by 404jv** [comment]
Fechado com o #34
