### ISSUE TITLE
Passar baseURL do axios para um .env

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#36]
Atualmente nosso arquivo `api.ts` está assim:
```ts
import axios from "axios";

const api = axios.create({
  baseURL: "http://192.168.0.194:3333",
});

export { api };
```
O problema aí é que cada um tem um IP diferente e sempre quando alguém comitta o seu IP, troca o de todo mundo.
Para resolver isso cria uma variável em um `.env` chamada BASE_URL e assim podemos ter acesso a ela com `process.env.BASE_URL`.

**Detalhes**
- Usamos a lib `dotenv`.
- Pesquise em qual arquivo seria melhor para importar o `dotenv` para conseguirmos ter acesso as variáveis.

**To do**
- [ ] Instalar o `dotenv` pela documentação oficial
- [ ] Importar o `dotenv` no arquivo principal (que você pesquisou e achou qual é)
- [ ] Criar a variável `BASE_URL` e usar no arquivo `api.ts`

**Comment by jvolima** [comment]
👋

**Comment by 404jv** [comment]
Fechado com a #55
