### ISSUE TITLE
Remover os espaços inúteis dos inputs antes de enviar a request

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#37]
No meu celular quando o teclado corretor completa meu email no input de login ou cadastro fica um espaço no final e isso vai fazer dar erro no login e no cadastro vai colocar meu email não como "joaovictorramalho7@gmail.com" e sim "joaovictorramalho7@gmail.com " não só nos inputs de email tá acontecendo isso e sim em todos.

Isso não é pra ser difícil, só achar como remove os que sobraram. Se o usuário escrever um username como "  404jv " pega se string e remove os espaços inúteis e envia para o back como "404jv" e a mesma coisa para os campos de email e nome.

**Detalhes**
- Os componentes que tem inputs são: SignUp, NextSignUp, SignIn.
- Apenas os campos de email, username e nome serão modificados. 
- Um nome como "João Victor " deve ficar "João Victor".
- Campos como senha e bio não precisam mudar.

**Comment by jvolima** [comment]
👋

**Comment by jvolima** [comment]
👋

**Comment by 404jv** [comment]
Fechada com a #42
