### ISSUE TITLE
Documento de requisitos para 30/04

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#40]
Essa não é código, mas é importante. Fazer a descrição de todas as funcionalidades e de cada regra de negócio.

- [x] Entender como escreve os requisitos
- [x] Escrever todos os requisitos

**Comment by alqui290** [comment]
Documento em progresso

**Comment by jvolima** [comment]
👋

**Comment by 1SyuLi** [comment]
👍

**Comment by 404jv** [comment]
Fechada :rocket:
