### ISSUE TITLE
Tipagem do ReactNavigation

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#50]
Isso aqui não vai mudar em questão de experiência do usuário, mas muda a qualidade do nosso código. Boas práticas em código é o que faz um bom programador, não basta só fazer funcionar. Então, é bom a gente manter boas práticas aqui no nosso repositório, até porque a gente não quer ver futuros devs ou recrutadores(a) vendo nosso código e achando feio.

Essa issue é bem simples, é só Tipar os parâmetros do `ReactNavigation` que está no [`index.d.ts`](https://github.com/404jv/dev-landia/blob/5b9c412261c71bc198695647fde01bd3e91562d1/mobile/src/%40types/navigation/index.d.ts#L9):
```ts
interface NextSignUpProps {
  userData: {
    name: string;
    email: string;
    user: string;
  };
}

export declare global {
  namespace ReactNavigation {
    interface RootParamList {
      Home: undefined;
      Activity: undefined;
      Achievements: undefined;
      Perfil: undefined;
      SignIn: undefined;
      SignUp: undefined;
      NextSignUp: NextSignUpProps;
      FinishSignUp: undefined;
      Nada: undefined;
    }
  }
}
```
Atualmente só o `NextSignUpProps` está tipado. Não manjo muito de RN nem de `ReactNavigation`, vocês sabem mais do que eu, portanto, se quiserem explicar o porque do `Nada: undefined;` vou agradecer. Caso só foi feito para teste e esquecido aí pode remover. 

**To do**
- [ ] Tipar as que precisam
- [ ] Editar o "Nada" da interface;

**Comment by 1SyuLi** [comment]
🔥

**Comment by 404jv** [comment]
Fechada com a #63
