### ISSUE TITLE
Arrumar os problemas do Eslint

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#52]
## Issue de 2 pontos

Essa issue é na mesma ideia da #50. Importantíssimo manter a padronização do código, sei que as vezes o Eslint é chato mas alguém tem que fazer o papel de "advogado do capeta" pois se não nosso código fica "espaguete" ou "porco" (como dizem na comunidade dev) e não queremos isso.

Atualmente no nosso código temos diversos comentários que desativam o Eslint (alguns feitos por mim kk) e vamos mudar isso - não é preciso remover todos - e sim diminuir eles. Começando pelos que reclamam do index de array sendo usado como chave do componente:
```tsx
<OptionEditorCode
  // eslint-disable-next-line react/no-array-index-key
  key={index}
  onPress={() => handleDeleteCodeFromEditor(index)}
>
```
Código acima está no componente [Editor - Linha 43](https://github.com/404jv/dev-landia/blob/5b9c412261c71bc198695647fde01bd3e91562d1/mobile/src/components/Editor/index.tsx#L43), no momento em que a gente fez esse comentário fazia sentido desativar o Eslint por conta de não termos o ID da opção, mas agora temos e não precisamos usar mais esse comentário.

Outro que precisamo remover da aplicação é esse:
```ts
export function Home(): JSX.Element {
  const theme = useTheme();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const navigation = useNavigation<any>();
```
O Eslint reclama quando usamos o tipo `any` por um motivo, e por favor, **não use o any no código**. Caso tenha alguma dúvida de como tipa algum parâmetro, pesquisa no google ou faça uma pergunta em alguma comunidade. Por fim, tem outros tipos de comentários de desativação, o máximo que você conseguir remover deles melhor.

**Detalhes**
- Existe alguns que não vai dá para tirar, então, deixa no código que mais para frente podemos alterar as regras do Eslint.
- Você pode usar a ferramenta de pesquisa no código do vscode para pesquisar por `// eslint`, vai aparecer todos os comentários de desativação, remova todos que conseguir.

**Comment by jvolima** [comment]
👋

**Comment by 404jv** [comment]
Fechada com a #54
