### ISSUE TITLE
Ordenação de fase e arrumar problema com NaN

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#57]
Novamente a Home! Nessa issue tem duas tarefas beeeem simples. A **primeira** é inverter a direção das fases na home, atualmente está assim:

<img src="https://user-images.githubusercontent.com/53544964/166166523-ecfbc2e5-4816-4bbd-a302-8aa77b163208.png" width="200">

Ou seja, a estrutura está:
- Mapa 1
- Mapa 2
- etc...

A meta é ficar:
- etc...
- Mapa 2
- Mapa 1

Assim conseguimos dar esse "feeling" de evolução (pois ninguém evolui indo pra baixo, né?) :smile:.

Já a **segunda** vamos mudar esse "NaN%" que está aparecendo. Muito simples, o problema é existe diversas fases no app e nem todas o usuário vai ter acesso, pois ele pode não estar no nível ainda, ou seja, a fase está bloqueada e quando isso acontece o back-end não vai retornar o `current_level` da fase, então, se tentarmos acessar essa chave no objeto vai está um `undefined`. 

**Exemplo de fase DESBLOQUEADA**
```json
{
  "id": "585413b4-ca9f-4d22-a3a2-a8272e658425",
  "map_id": "654b369c-8459-4c7e-be93-b74531c7f8de",
  "title": "Fase 2",
  "type": "practice",
  "markdown_text": null,
  "description": "descrição fase 2",
  "max_level": 3,
  "order": 0,
  "created_at": "2022-05-01T15:24:11.619Z",
  "current_level": 0 // Olha o current level aqui!!
},
```

**Exemplo de fase BLOQUEADA**
```json
{
  "id": "2895a53e-b43f-43fb-8ae8-ef7bf4da1f00",
  "map_id": "2fad788d-e552-4232-ab72-ff4aa3ef6378",
  "title": "Fase 1",
  "type": "practice",
  "markdown_text": null,
  "description": "descrição fase 1",
  "max_level": 3,
  "order": 0,
  "created_at": "2022-05-01T15:24:11.659Z" // Não tem current level =(
},
```
PS: a regra é para todas as fases, independe do tipo de fase (teórica ou prática).

Para corrigir isso faça uma verificação no `current_level` se for `undefined` retorna um ícone de cadeado no lugar da % e deixa a barra de progresso zerada do jeito que é por padrão.

**To do**
- [ ] Inverter as fases.
- [ ] Colocar o ícone de cadeado quando a fase está bloqueada.

**Comment by jvolima** [comment]
👋

**Comment by 404jv** [comment]
Fechada com a #59
