### ISSUE TITLE
Fichamento Duolingo 28/05

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#70]
Os dois artigos estão em inglês, seja quem pegar - é bom ter o inglês afiado. Por mais que o estudo do Duolingo seja para aprendizado de idiomas, ainda acho que vai ajudar bastante no nosso app, então, esse é um fichamento muito importante pra gente.

Eles fizeram no blog deles:
![image](https://user-images.githubusercontent.com/53544964/169834470-9b74e267-a451-4045-b84e-9d2cfeb6ba9d.png)
_Disponível em: https://blog.duolingo.com/how-we-learn-how-you-learn/_
E deixaram um PDF:
![image](https://user-images.githubusercontent.com/53544964/169834558-12e2e5c2-1c62-4b9a-af26-2292162f6338.png)
_Disponível em: https://aclanthology.org/P16-1174.pdf_

Como são bem curtinhos cabe em uma Issue, mas se **você quiser** separa os dois fichamentos lá no Docs, ou deixa junto msm.

**Objetivos**
- Procure e destaque o máximo de adjetivos que pode ser usado para defender nosso app.
- O principal tema que estamos procurando explicar é **aprendizado com repetição espaçada**, pois vai ser usado no nosso app.

Além disso, queremos saber se essa mesma metodologia funciona para o aprendizado de programação, mas pra saber disso precisamos entender como ela funciona antes.

**Comment by jvolima** [comment]
me

**Comment by 404jv** [comment]
Fechada
