### ISSUE TITLE
Arrumar documento de requisitos 30/05

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#71]
Como o professor destacou na reunião: é necessário escrever as principais tecnologias usada na construção do APP e mostrar quantos XP e Coins o usuário ganha.

Essas daqui deverão ser citadas:
- Node (para o servidor)
- Javascript com Typescript (para escrever o código)
- React Native e Expo (para o aplicativo)
- PostgreSQL (banco de dados)
- Yarn (gerenciador de dependência)

Caso tiver mais algum que você acha necessário adiciona na lista. Não sei exatamente em qual local do documento é preciso adicionar isso, acho que o David sabe.

Sobre o XP, coins e leveis das fases: quando o usuário termina uma fase ele ganha **5 XP**, **1 coin** e **um level na fase**. 

Por exemplo, o Joãozinho tem:
- Fase no level 2
- Coins: 2
- XP: 4

Quando Joãozinho terminar a fase vai passa a ter:
- Fase no level 3
- Coins: 3
- XP: 9

Simples, não? Deve ser destacado isso (quanto o usuário ganha) na parte da fase lá no documento de requisitos.

**To do**
- [ ] Adicionar tecnologias no doc
- [ ] Adicionar recompensas no doc

**Comment by alqui290** [comment]
Aguardando casos de uso

**Comment by alqui290** [comment]
concluida
